# Generated by Django 3.2.5 on 2021-07-27 18:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20210726_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(error_messages={'unique': 'این نام در سیستم ثبت شده است.'}, max_length=100, unique=True, verbose_name='نام سازمان'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number invalid', regex='^[0][9]\\d{9}$')], verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
